# Generated by Django 4.2.1 on 2023-05-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_criador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='carga_horario',
            new_name='carga_horaria',
        ),
    ]
